name: Docker Build

on:
  push:
    paths: 
      - .github/workflows/docker.yml
      - .devcontainer/Dockerfile
      
  pull_request:
    paths: 
      - .github/workflows/docker.yml
      - .devcontainer/Dockerfile
  schedule:
    - cron: '0 0 1 * *'

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          persist-credentials: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2      

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image melodic
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .devcontainer/Dockerfile
          build-args: [ROS_DISTRO=melodic]
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/sjtu-cyberc3/cpptemplates:melodic
      
      - name: Build and push image noetic
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .devcontainer/Dockerfile
          build-args: [ROS_DISTRO=noetic]
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/sjtu-cyberc3/cpptemplates:noetic
           
      - name: Build and push image galactic
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .devcontainer/Dockerfile
          build-args: [ROS_DISTRO=galactic]
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ghcr.io/sjtu-cyberc3/cpptemplates:galactic